"""create_rag_tables

Revision ID: 346fc46d33f7
Revises: 1f7ebc8e895f
Create Date: 2026-04-30 07:29:27.163827
"""

from typing import Sequence, Union

import sqlalchemy as sa
import pgvector.sqlalchemy  # Eklendi: pgvector destegi icin
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346fc46d33f7'
down_revision: Union[str, None] = '1f7ebc8e895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('MEB', 'YOK_TEZ', 'MAKALE', 'SAGLIK_BAK', name='source_type_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_sources_file_hash'), 'academic_sources', ['file_hash'], unique=True)
    op.create_index(op.f('ix_academic_sources_is_indexed'), 'academic_sources', ['is_indexed'], unique=False)
    op.create_table('rag_responses',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('disability_type', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('embedding_latency_ms', sa.Float(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_responses_student_id'), 'rag_responses', ['student_id'], unique=False)
    op.create_index(op.f('ix_rag_responses_teacher_id'), 'rag_responses', ['teacher_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('page_numbers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('negative_feedback_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['academic_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_chunks_negative_feedback_count'), 'source_chunks', ['negative_feedback_count'], unique=False)
    op.create_index(op.f('ix_source_chunks_source_id'), 'source_chunks', ['source_id'], unique=False)
    op.create_table('response_chunks',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['rag_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', 'chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_chunks')
    op.drop_index(op.f('ix_source_chunks_source_id'), table_name='source_chunks')
    op.drop_index(op.f('ix_source_chunks_negative_feedback_count'), table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index(op.f('ix_rag_responses_teacher_id'), table_name='rag_responses')
    op.drop_index(op.f('ix_rag_responses_student_id'), table_name='rag_responses')
    op.drop_table('rag_responses')
    op.drop_index(op.f('ix_academic_sources_is_indexed'), table_name='academic_sources')
    op.drop_index(op.f('ix_academic_sources_file_hash'), table_name='academic_sources')
    op.drop_table('academic_sources')
    # ### end Alembic commands ###
