"""add observations and materials

Revision ID: b366e36eed02
Revises: 2dc2654d528f
Create Date: 2026-05-07 07:47:30.862281
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b366e36eed02'
down_revision: Union[str, None] = '2dc2654d528f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('material_type', sa.Enum('SOCIAL_STORY', 'PECS_CARD', name='material_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('interest_topic', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'COMPLETED', 'FAILED', name='material_status_enum'), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('BEHAVIOR', 'ACADEMIC', 'CRISIS', 'SOCIAL', 'COMMUNICATION', name='observation_category_enum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('antecedent', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=False),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('transcription_latency_ms', sa.Float(), nullable=True),
    sa.Column('structuring_latency_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('materials')
    # ### end Alembic commands ###
