"""add_iep_drafts_table

Revision ID: c76f68a15c39
Revises: 4ad09a56f687
Create Date: 2026-05-04 07:11:30.400913
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c76f68a15c39'
down_revision: Union[str, None] = '4ad09a56f687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iep_drafts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'finalized', name='iep_status_enum'), nullable=False),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iep_drafts_student_id'), 'iep_drafts', ['student_id'], unique=False)
    op.create_index(op.f('ix_iep_drafts_teacher_id'), 'iep_drafts', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iep_drafts_teacher_id'), table_name='iep_drafts')
    op.drop_index(op.f('ix_iep_drafts_student_id'), table_name='iep_drafts')
    op.drop_table('iep_drafts')
    # ### end Alembic commands ###
